# Generated by Django 5.2.6 on 2025-09-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
