# Generated by Django 5.2.6 on 2025-12-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0004_remove_orderdetail_price_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Дневной номер заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet_shop.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('processing', 'В обработке'), ('picking', 'В сборке'), ('picked', 'Собран'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet_shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet_shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet_shop.category', verbose_name='Категория'),
        ),
    ]
