# Generated by Django 5.2.6 on 2025-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0005_order_order_number_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('processing', 'В обработке'), ('picking', 'В сборке'), ('picked', 'Собран'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='processing', verbose_name='Статус'),
        ),
    ]
