# Generated by Django 5.2.6 on 2025-12-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('В обработке', 'В обработке'), ('В сборке', 'В сборке'), ('Собран', 'Собран'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='В обработке', verbose_name='Статус'),
        ),
    ]
