# Generated by Django 5.2.6 on 2025-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
