# Generated by Django 5.2.6 on 2025-12-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0008_customer_picture_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='customers', verbose_name='Изображение'),
        ),
    ]
